<#
.SYNOPSIS
    Generates and verifies evidence file digests for the G0/G1/G2 gate records.

.DESCRIPTION
    Evidence reports quote the SHA-256 digests of the documents they depend on.
    A hand-copied digest is stale the moment either file is edited, and a stale
    digest is worse than no digest: it looks like verification while asserting
    something false.

    So the digests live in one generated file, evidence/manifest.sha256, and the
    reports reference this script rather than carrying inline values. Regenerate
    after any evidence edit; -Verify fails nonzero when a digest has drifted.

    This records the same lesson as the audit chain: the evidence must be
    checkable by a party that did not write it, and the check must not depend on
    the writer's memory.

.EXAMPLE
    powershell -NoProfile -ExecutionPolicy Bypass -File evidence/evidence.sha256.ps1
    Regenerates the manifest from the current evidence tree.

.EXAMPLE
    powershell -NoProfile -ExecutionPolicy Bypass -File evidence/evidence.sha256.ps1 -Verify
    Verifies every listed digest. Exit code 1 on any drift.
#>
[CmdletBinding()]
param(
    [switch]$Verify
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# The manifest describes every evidence file except itself.
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$manifest = Join-Path $root 'manifest.sha256'

$files = Get-ChildItem -Path $root -Recurse -File |
    Where-Object { $_.FullName -ne $manifest } |
    Sort-Object FullName

if (-not $files -or $files.Count -eq 0) {
    throw "no evidence files found under $root"
}

function Get-RelativePath([string]$full) {
    return $full.Substring($root.Length).TrimStart('\', '/')
}

if ($Verify) {
    if (-not (Test-Path -LiteralPath $manifest)) {
        Write-Error "manifest not found: $manifest (run without -Verify to generate it)"
        exit 1
    }

    $expected = @{}
    foreach ($line in [IO.File]::ReadAllLines($manifest)) {
        $trimmed = $line.Trim()
        if (-not $trimmed -or $trimmed.StartsWith('#')) { continue }
        # sha256sum format: <hex><two spaces><path>
        if ($trimmed -notmatch '^([0-9a-f]{64})\s+(.+)$') {
            Write-Error "unparseable manifest line: $trimmed"
            exit 1
        }
        $expected[$Matches[2]] = $Matches[1]
    }

    $drift = 0
    $listed = 0
    foreach ($path in $expected.Keys) {
        $full = Join-Path $root ($path -replace '/', '\')
        if (-not (Test-Path -LiteralPath $full)) {
            Write-Host "MISSING  $path" -ForegroundColor Red
            $drift++
            continue
        }
        $listed++
        $actual = (Get-FileHash -LiteralPath $full -Algorithm SHA256).Hash.ToLower()
        if ($actual -ne $expected[$path]) {
            Write-Host "DRIFT    $path" -ForegroundColor Red
            Write-Host "           expected $path = $($expected[$path])" -ForegroundColor Red
            Write-Host "           actual         = $actual" -ForegroundColor Red
            $drift++
        }
    }

    # An evidence file that is not in the manifest is an unrecorded claim.
    $unlisted = 0
    foreach ($f in $files) {
        $rel = Get-RelativePath $f.FullName
        if (-not $expected.ContainsKey($rel)) {
            Write-Host "UNLISTED $rel" -ForegroundColor Yellow
            $unlisted++
        }
    }

    if ($drift -gt 0) {
        Write-Host ""
        Write-Host "evidence digest check FAILED: $drift drifted, $listed checked" -ForegroundColor Red
        exit 1
    }
    if ($unlisted -gt 0) {
        Write-Host ""
        Write-Host "evidence digest check FAILED: $unlisted file(s) not recorded in the manifest" -ForegroundColor Red
        exit 1
    }

    Write-Host "evidence digest check passed: files=$listed drift=0 unlisted=0"
    exit 0
}

$lines = @(
    '# Evidence manifest. Generated by evidence/evidence.sha256.ps1 -- do not edit by hand.'
    '# Format is sha256sum: <64 hex chars><two spaces><path relative to this file>.'
    '# Verify with: powershell -NoProfile -ExecutionPolicy Bypass -File evidence/evidence.sha256.ps1 -Verify'
    ''
)
foreach ($f in $files) {
    $hash = (Get-FileHash -LiteralPath $f.FullName -Algorithm SHA256).Hash.ToLower()
    $lines += "$hash  $(Get-RelativePath $f.FullName)"
}

[IO.File]::WriteAllLines($manifest, $lines, (New-Object Text.UTF8Encoding($false)))
Write-Host "wrote $manifest ($($files.Count) files)"
Get-Content -LiteralPath $manifest | Where-Object { $_ -and -not $_.StartsWith('#') } | ForEach-Object { "  $_" }
